# Versions:
# POD v1
# Service v1
# ReplicaSet apps/v1
# Deployment apps/v1
---
apiVersion: vi

kind: Pod

metadata:
    name: myapp-pod
    labels: 
        app: myapp

spec:
    containers:
        - name: Nginx-Container
          image: nginx
        
# kubectl create -f pod-definition.yml    : This cmd is used to create the pod inside the worker nodes
# kubectl get pods:                       : This cmd is used for to list the running pods
# kubectl describe pod pod-definition.yml : To see the detail information about the pod